### ISSUE TITLE
EVA 3 - BMG vs Cable management Conflict

### ISSUE THREAD

**Issue by bubujoe** [EVA-3D/eva-main#80]
BMG stepper motor is in conflict with the main cable management

![image](https://user-images.githubusercontent.com/80191627/167791643-28dd036d-f4c0-474a-ac52-a0af1836acf1.png)

**Comment by pkucmus** [comment]
There is an alternative cable mount for it, I forgot to document it

**Comment by pkucmus** [comment]
Fixed in 3.0.2

**Comment by david-antos** [comment]
The "fat" cable guide mount doesn't actually fix that completely: the BMG motor is about 2 mm too deep and conflicts even with the cable guide *mount*, not only with the cable guide ("the basket"). So something like, e.g. https://www.printables.com/model/203244-eva-3-modified-cable-guide-for-bmg-extruder is necessary (this solution works for 5015 fans, but conflicts with 4028, though).

**Comment by olivbd** [comment]
> The "fat" cable guide mount doesn't actually fix that completely: the BMG motor is about 2 mm too deep and conflicts even with the cable guide _mount_, not only with the cable guide ("the basket"). So something like, e.g. https://www.printables.com/model/203244-eva-3-modified-cable-guide-for-bmg-extruder is necessary (this solution works for 5015 fans, but conflicts with 4028, though).

I've the same issue with 4028 fan... You can check my work here: https://www.printables.com/model/261446-eva-3-modified-cable-guide-for-bmg-extruder-with-4
